name: flutter_chart_libraries
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fl_chart: ^0.55.2
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.0
  build_runner: ^2.2.0
  flutter_lints: ^2.0.1
  vector_math: ^2.1.2

flutter:
  uses-material-design: true

